title: Recipes
description: A simple collection of cooking recipes
theme: minima

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-anchor-headings

defaults:
  - scope:
      path: "recipes"
      type: "pages"
    values:
      layout: "default"
      permalink: /:basename